/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicGoogleDriveCallbackRouteImport } from './routes/api/public/google/drive-callback'
import { Route as ApiPublicHooksDriveSyncRouteImport } from './routes/api/public/hooks/drive-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleDriveCallbackRoute =
  ApiPublicGoogleDriveCallbackRouteImport.update({
    id: '/api/public/google/drive-callback',
    path: '/api/public/google/drive-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDriveSyncRoute = ApiPublicHooksDriveSyncRouteImport.update({
  id: '/api/public/hooks/drive-sync',
  path: '/api/public/hooks/drive-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/google/drive-callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/hooks/drive-sync': typeof ApiPublicHooksDriveSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/google/drive-callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/hooks/drive-sync': typeof ApiPublicHooksDriveSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/google/drive-callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/hooks/drive-sync': typeof ApiPublicHooksDriveSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/google/drive-callback'
    | '/api/public/hooks/drive-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/google/drive-callback'
    | '/api/public/hooks/drive-sync'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/google/drive-callback'
    | '/api/public/hooks/drive-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleDriveCallbackRoute: typeof ApiPublicGoogleDriveCallbackRoute
  ApiPublicHooksDriveSyncRoute: typeof ApiPublicHooksDriveSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/drive-callback': {
      id: '/api/public/google/drive-callback'
      path: '/api/public/google/drive-callback'
      fullPath: '/api/public/google/drive-callback'
      preLoaderRoute: typeof ApiPublicGoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drive-sync': {
      id: '/api/public/hooks/drive-sync'
      path: '/api/public/hooks/drive-sync'
      fullPath: '/api/public/hooks/drive-sync'
      preLoaderRoute: typeof ApiPublicHooksDriveSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicGoogleDriveCallbackRoute: ApiPublicGoogleDriveCallbackRoute,
  ApiPublicHooksDriveSyncRoute: ApiPublicHooksDriveSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
